language: node_js
node_js:
  - "lts/*"
cache: yarn
script:
  - npm run build
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: DvIPbgk3GgWB7w3fC2/cFeE9ToXLvgYh6kUaf9ZIUIK78ayX9JSl74GLvn/iHf2Xi9jAAh84bESFk43fw+XcbQGy/MeWoJjcawi7mZDe3dailInqJxx1GvqisZYwlfNWkBTwLob14ha+AXqZEDBG3vuyM7qxw7lH/dbZESFGf42IBPs1DpCdyPrw/U0XjuBZ7rs7KBi+4cQ73rpbZg7FVTMTtVaQReYtyzpp7B/cKNSNpc0tHR71VQkd2z9P8UgsO1wCNgcj+H/ReXxeBEI8vtvoaA5NWZ0S6P58MPpTAvP6YfEjJV2MCX6aYqusuxcD7ugH7UBGj5X21FZhx/PmtNgZpd6L2bYm+yAzh4tg/r5Alf5y3bjJuTzxR9vl48EZMKUGMBgYxVvWiIAacW+X0r1rqCjiTviqPRjlY+kFQP9jl8edrvpVGmyOTiNus+W8AHn4EB4XDzedTidY+GBYDe4zJb/7Z4SDbniciFyCDn/1KrIiBQdhffR1fX3vg/hpEn49uo6e6q8/gbSCFw3TB8LKLDBp1Ee8K5M/JvOy2RPCxOBZWOtIZlu5mrXlyazMhvzAcBk/bLg3vBNy5KGh7HGcOE3zmrvtPTGqKnhynA0vPHrUyGtFR9Oaka2MInnxEnXJ+lmC3mZ11zxR7tItVEXwsUn0gDZvDU1dsm7sEvI=
  app: rens-ui
  on:
    branch: example
