language: node_js
node_js:
  - "lts/*"
cache: yarn
script:
  - npm run build
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: pRGoH6Clb/2CaO7BBEwYM7L7oNvLr0ia4l/we+fr4oqnMhWlrUges/zlk91h33TU22GZbV9F1h2p2Baqo2n1BkFXfymTPzRv3RbSY6eRsqdHvNz4LEU5x5jp56bAhVYip0in7VA/XqPPtRhChXJN9t520GLAgoaR4wWV6CC/kM8iRuB1f+42l8gMGK7FoITLbxltkW3EVINwd3fj/qAbL5DAMe6GgIOdhopxeb9Q69nQ7VZeMx6koXNPflTm5StZyYv2nXF2FRo6WjqkG+y0vVW/gH6FWKMe7RdDcJI/w7l7OvXCM1Knq+8tBHdnLJNPKidZ/qLtQutLChpiQY9UmftOoIhZ6ZHLGiOhdFRug4VRDWlhHiBjanz1+W8Nb8HXvHUh6BmJkReVSdhtVda7J2Yo9Z0VfcO9LNs+UBr8LSv1RE+hSfQig2zlPGnl+Px9JumvBNce2WYk+Q1JkwD7Intnvc1r/lxjsY9ZRVxXORljBBgp5CcXKMLw2vY1vJJ398esijoWWm1JRvcqy1vqDPkFOVNksbNTYRyjmL5rgiBnWrcBFSaECCaLcZRg9BY84h58Fj4j3cFGAGd3PKHyljZ1/R/mnSZ2P/aWuCwhXi9VwZMvtUpyYMSCp6IARPRoWJc/lGohIQ8E7vz9fY0h/5UErAngsWwoXaT3ckuEfao=
  app: rens-ui
  on:
    branch: example
