language: node_js
node_js:
  - lts/*
cache: npm
script:
  - npm run build
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: q3Zkmeao0M3LICJMJ9pR8KaKdW8LYGHsOwpbgTnNBzRrokKVHxcRWbN7xwDREg56Yb1FIxccqMT9mHmQPqABTXPNFxyZpe7GCtylQbsG4+zD3oiqLsGbe2746A5h2VebJFZMdnhBvSO48E+442f+ZdU4ojCJMcl/Nnz85SZzIymHiUNja19H+o54aOa3HDE1w+su+jW7OfnAichf9sxg2Ph7noD2fHDWS+5ISwsxP9o2M/N7DZOcCaRM1HwrQ+DHYPL5vwUaq1VxJ1RC4viLqatTQluBr79P5YXlAd8zMCYEFdwq4nsIuAprWOIB1Evkr+92/BDZqsDyA0qIVHcfThYw7cyEGN08pvrphkXStUCHjZb7p157ddvsEuo3GypNaACgR7lukeksn7zFIOUvmUMYOIx6G7aMqmcrRhESL1CCd994haDB/C1o88bj02osRVbELIV7MwZMwMLzWr0GuGH0xfweUJot8nVBYtlj1XV91ZU65lN23EIEdQb8NtMMAGdpQ0/qMOy+85AavdM6jMcKUcBQSKz6veaFw8/prNMuCy8N79w1gVqIOKNpceMmHu+iAs6zZKpTTIBxLnSb3bJEtIAA604gUdE5rC9+I3m8rQWIVJX0ImQwvCDR3ByP6iIdFt+slyz/m89XxLQyoEvh7eDSLZJOxjNYecSgVy8=
  app: rens-ui
  on:
    branch: master
