language: node_js
node_js:
  - "lts/*"
cache: yarn
script:
  - npm run build
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: Yl2LDci08xNAsyVuTJqRHGXZ74mAKjGBnbzE/Bapq4r2zBkLWjgnipJBF9Stb+5Tc/20VD/RiRBMuWAt03Hy8eaL0o/L/N3I0VKHWhsEzzjjONznq6inKjnObECQ8zBYORM7T8gKAXUEP0NldRHtooaWp4akVWXQe+sYD4tUM2Lq1zretFyFb3WhmiVT+5okv8S0gVDRy0nKtRWbJ3whQsY0tr4iHvMaK8NV0mp974yAm34mDGD4nffjGWoW+54dL45zW2TPN1d90P7jurPKr4zBwKrIZXzbKCeKNoRr9XZzBYHib7ZIrg79pPbIQB9iS0611o4Jq3Q99BwdK0bDzolhGHQIwwU7xGOPsPTYX61+JR15gSoUs8oW8iSftMTCV4D/laGBvCqA0uYGHv914RADa6KlGKGjHzWUyl3wT72/3kqYGRcGnYY7VqXUfavjyVAhYhFVuf2qdH7bI1THH0gHFHiUm14iFLkeWqA8lLebHyG5RfDTJboNsSobLCAyTO1c740UQ6LWOPCGUWx9ptbDSMb2Wm1ZB9XuK3VuDomM4wWyIGY5395IUw8AN2WhSzJ9SlQnmGa6sEbciNJwCtmEwopST4gTm/jGaIlBCZbumOn0R5/MuZ40OO2dQUFY6t1QA+0gWlbTJVJUSh5NfXFoRGldP6lORGZqWpqgxiE=
  app: rens-ui
  on:
    branch: master
